name: Rust Build

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    container: jugeeya/cargo-skyline:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Link rust-std-skyline src
      run: mkdir ../rust-std-skyline-squashed && ln -s $XARGO_RUST_SRC ../rust-std-skyline-squashed/src
    - name: Build release NRO
      run: cargo skyline build --release
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: target/aarch64-skyline-switch/release/libKetchupMod.nro
    - name: Upload romfs artifact
      uses: actions/upload-artifact@v2
      with:
        name: KetchupMod
        path: romfs/KetchupModRomfs

# uncomment the build step below to build on every change to master.
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: prepare zip
      env:
        SMASH_PLUGIN_DIR: atmosphere/contents/01006A800016E000/romfs/skyline/plugins
      run: |
        mkdir -p ${{env.SMASH_PLUGIN_DIR}}
        cp plugin/libKetchupMod.nro ${{env.SMASH_PLUGIN_DIR}}/libKetchupMod.nro

        wget https://github.com/ultimate-research/nro-hook-plugin/releases/download/v0.1.1/libnro_hook.nro
        cp libnro_hook.nro ${{env.SMASH_PLUGIN_DIR}}/libnro_hook.nro

        wget https://github.com/ultimate-research/acmd_hook/releases/download/master/libacmd_hook.nro
        cp libacmd_hook.nro ${{env.SMASH_PLUGIN_DIR}}/libacmd_hook.nro

        wget https://github.com/Raytwo/ARCropolis/releases/download/v1.0.1/release.zip
        unzip release.zip

        mkdir -p ultimate/mods
        cp -r KetchupMod ultimate/mods
        
        zip -r KetchupMod.zip ultimate atmosphere
  
    - name: Update Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: folders
        tag: master
        name: master
        body: Build of KetchupMod from master.
        files: >
          KetchupMod.zip
  

